Seagate/cortx-monitor

low-level/sspl-ll.spec

HA resource agent creates state.txt file.
Problem: sspl-ll user doesn't have permission to read the state.txt file.
Solution: Assign ownership to sspl-ll and give read permission to user & group.

EOS-13167 - SSPL state file access issue (cortx-1.0)

---

low-level/sspl-ll.spec

HA resource agent creates state.txt file.
Problem: sspl-ll user doesn't have permission to read the state.txt file.
Solution: Assign ownership to sspl-ll and give read permission to user & group.

EOS-13167 - SSPL state file access issue (main)

---

low-level/framework/sspl_reinit
sspl_test/run_test.py

- Fix is to retain suoders.d/sspl by configuring puppet-agent
<pre>
<code>
Story Ref (if any): 
EOS-13693 - SSPL - Fixing sspl auth file getting removed by puppet-agent
</code>
</pre>
<pre>
<code>
After "EOS-12780 Release 2792 : Journalctl flooded with errors from sspl" fix, still observed auth error after long time sspl run.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
- Yes
</code>
</pre>
<pre>
<code>
- NA, log verification only.
</code>
</pre>

EOS-13693 - SSPL - Fixing sspl auth file getting removed by puppet-agent (cortx-1.0)

---

low-level/framework/sspl_reinit

- Fix is to retain suoders.d/sspl by configuring puppet-agent
<pre>
<code>
Story Ref (if any): 
EOS-13693 - SSPL - Fixing sspl auth file getting removed by puppet-agent
</code>
</pre>
<pre>
<code>
After "EOS-12780 Release 2792 : Journalctl flooded with errors from sspl" fix, still observed auth error after long time sspl run.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
- Yes
</code>
</pre>
<pre>
<code>
- NA, log verification only.
</code>
</pre>

EOS-13693 - SSPL - Fixing sspl auth file getting removed by puppet-agent (main)

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view

Added storage_type filter for manifest support data
Removed 5u84 and pods as storage_type and considered only rbod, virtual and jbod as storage type for the health view script
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-13436 : Improve healthview generation code

---

low-level/framework/utils/salt_util.py

- Use provisioner API instead of salt-call
- Make that class singleton
- Restructure
<pre>
<code>
EOS-13776: RAS: Failover/Failback downtime improvement
</code>
</pre>
<pre>
<code>
SSPL is taking more time to start in case of scenarios like failover. In case, it gets stopped for some reason.
</code>
</pre>
<pre>
<code>
SSPL is using salt-call to fetch pillar information which gets hang many times. And because of this, SSPL main thread also 
gets blocked. So, instead of salt-call, use of provisioner API will help.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
On dual Node setup:
Install RPM and intialize
Now, start the sspl resource in pacemaker cluster
Disable the resource and enable it again
Reboot the node
</code>
</pre>

EOS-13776: RAS: Failover/Failback downtime improvement

---

low-level/framework/sspl_ll_d

Modified the SSPL signal handler to disable handling of new SIGHUPs
while one is being processed
Signed-off-by: Archana Limaye <archana.limaye@seagate.com>
<pre>
<code>
SSPL signal handler does not ignore additional SIGHUPs while processing one SIGHUP
</code>
</pre>
<pre>
<code>
SSPL signal handler does not ignore additional SIGHUPs while processing one SIGHUP
</code>
</pre>
<pre>
<code>
Modified the SSPL code so that any additional SIGHUPs while one is being processed are ignored
</code>
</pre>
<pre>
<code>
- Yes
</code>
</pre>
<pre>
<code>
Deployed SSPL on VM.
Issued multiple SIGHUPs.
Ensured that only one SIGHUP is being handled and others are ignored; by checking the logs 
</code>
</pre>

Changes for EOS-13166 SSPL signal handler fix

---

low-level/framework/utils/consulstore.py
low-level/framework/utils/filestore.py
low-level/sensors/impl/generic/node_memory_fault.py
low-level/sensors/impl/platforms/realstor/realstor_disk_sensor.py

Signed-off-by: Vijay Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
Story Ref (if any):EOS-13850 
5U Disk fault alerts not seen after "pcs resource disable/enable consul-c1"
</code>
</pre>
<pre>
<code>
5U disks alerts not seen after disabling and enabling again consul agent
</code>
</pre>
<pre>
<code>
1. Data corruption was happening in the put method of consul when consul was disable and suddenly comes back during the consul connection retires. Fixed issue
2. Also added handing to skip alerts when consul connection is down.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Validated rpms on the hardware setup and observed that alerts are coming as per the expectation.
</code>
</pre>

EOS-13850 5U Disk fault alerts not seen after consul disable and enable

---

low-level/framework/utils/consulstore.py
low-level/framework/utils/filestore.py
low-level/sensors/impl/generic/node_memory_fault.py
low-level/sensors/impl/platforms/realstor/realstor_disk_sensor.py

Signed-off-by: Vijay Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
Story Ref (if any):EOS-13850 
5U Disk fault alerts not seen after "pcs resource disable/enable consul-c1"
</code>
</pre>
<pre>
<code>
5U disks alerts not seen after disabling and enabling again consul agent
</code>
</pre>
<pre>
<code>
1. Data corruption was happening in the put method of consul when consul was disable and suddenly comes back during the consul connection retires. Fixed issue
2. Also added handing to skip alerts when consul connection is down.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Validated rpms on the hardware setup and observed that alerts are coming as per the expectation.
</code>
</pre>

EOS-13850 5U Disk fault alerts not seen after consul disable and enable for main branch

---

low-level/sspl-ll.spec

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14288
</code>
</pre>
<pre>
<code>
Permissions are not preserved when creating backup of cached data
-bash-4.2$ ls -l /opt/seagate/backup/1.0.0/sspl/data/
total 8
drwxr-xr-x 3 root root 4096 Oct  2 02:34 server
-rw-r--r-- 1 root root   13 Oct  7 07:19 state.txt
This creates problem when backup is restored at /var/cortx/sspl/ . SSPL can't generate files under this directory because of 
root:root permission on cached directory and give PermissionDenied  Error when creating files.
</code>
</pre>
<pre>
<code>
Added -p flag in cp command which preserve mode,ownership,timestamps
</code>
</pre>
<pre>
<code>
- [x ] Yes
</code>
</pre> …

EOS-14288: Preserve ownership when copying  and restoring cached data

---

low-level/sspl-ll.spec

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14288
</code>
</pre>
<pre>
<code>
Permissions are not preserved when creating backup of cached data
-bash-4.2$ ls -l /opt/seagate/backup/1.0.0/sspl/data/
total 8
drwxr-xr-x 3 root root 4096 Oct  2 02:34 server
-rw-r--r-- 1 root root   13 Oct  7 07:19 state.txt
This creates problem when backup is restored at /var/cortx/sspl/ . SSPL can't generate files under this directory because of 
root:root permission on cached directory and give PermissionDenied  Error when creating files.
</code>
</pre>
<pre>
<code>
Added -p flag in cp command which preserve mode,ownership,timestamps
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code> …

EOS-14288: Preserve ownership when copying and restoring cached data

---

low-level/files/opt/seagate/sspl/conf/setup.yaml

<pre>
<code>
With changes in EOS-12885 and EOS-13719  the file name and path for build-ees-ha-args.yaml has changed
This needs to be addressed in SSPL
</code>
</pre>
<pre>
<code>
With changes in EOS-12885 and EOS-13719  the file name and path for build-ees-ha-args.yaml has changed
This needs to be addressed in SSPL
</code>
</pre>
<pre>
<code>
Modified the file name build-ees-ha-args.yaml to build-ha-args.yaml and updated the file path also 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Custom build will be made with changes in all components and that will be deployed/tested  on the hardware 
</code>
</pre>

Changes for EOS-14128 SSPL: Need to remove ees from fillename build-ees-ha-args.yaml 

---

low-level/files/opt/seagate/sspl/conf/setup.yaml

<pre>
<code>
With changes in EOS-12885 and EOS-13719  the file name and path for build-ees-ha-args.yaml has changed
This needs to be addressed in SSPL
</code>
</pre>
<pre>
<code>
With changes in EOS-12885 and EOS-13719  the file name and path for build-ees-ha-args.yaml has changed
This needs to be addressed in SSPL
</code>
</pre>
<pre>
<code>
Modified the file name build-ees-ha-args.yaml to build-ha-args.yaml and updated the file path also 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Custom build will be made with changes in all components and that will be deployed/tested  on the hardware 
</code>
</pre>

    Changes for EOS-14128 SSPL: Need to remove ees from fillename build-ees-ha-args.yaml

---

low-level/json_msgs/messages/sensors/host_update.py
low-level/tests/manual/mock-halon.py
sspl_test/alerts/os/test_node_host_data_sensor.py

…lert, alert triggered as system alert.
Modified the RESOURCE_TYPE to give more information about the resource
Signed-off-by: Archana Limaye <archana.limaye@seagate.com>
<pre>
<code>
Alert name was coming as system alert for the node memory alert
</code>
</pre>
<pre>
<code>
Resource type node:os:system was used for the alert so it was not clear that the alert was for system memory  
</code>
</pre>
<pre>
<code>
Modified the resource type in node_data_msg_handler - HostUpdateMsg from node:os:system to node:os:system_memory
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Created the RPM ; generated the memory alert and confirmed on rabbitmq_reader that the new  reource_type is displayed in the alert alert 
</code>
</pre>

Changes for EOS-14403 Alert name issue on GUI: instead of memory alert, alert triggered as system alert.

---

low-level/files/opt/seagate/sspl/bin/constants.sh
low-level/files/opt/seagate/sspl/bin/sspl_setup_consul
sspl_test/constants.sh
sspl_test/framework/base/sspl_constants.py
util-scripts/sspl_dev_cfg_update_in_consul

<pre>
<code>
Consul installation and binaries are moved out of Hare and is part of provisioner for installation. Please refer to ticket EOS-14262 for more information.
As a workaround, a symlink is created to /opt/seagate/cortx/hare/bin/consul for product to continue to work. This ticket is for component to remove the dependency on hare path hardcoded in the code so that symlink can be removed.
If it is already done in your component then mark this ticket resolved not required anymore.
Once all required components have made the changes. The code for creating the symlink during installation will be removed and no workaround required for consul binaries.
</code>
</pre>
<pre>
<code>
Provisioner installs consul and binary will be available in /usr/bin
</code>
</pre>
<pre> …

EOS-14380: Remove dependency of Consul hardcoded path inside Hare and  move to /usr/bin/consul - SSPL - (cortx-1.0)

---

low-level/files/opt/seagate/sspl/bin/constants.sh
low-level/files/opt/seagate/sspl/bin/sspl_setup_consul
sspl_test/constants.sh
sspl_test/framework/base/sspl_constants.py
util-scripts/sspl_dev_cfg_update_in_consul

<pre>
<code>
Consul installation and binaries are moved out of Hare and is part of provisioner for installation. Please refer to ticket EOS-14262 for more information.
As a workaround, a symlink is created to /opt/seagate/cortx/hare/bin/consul for product to continue to work. This ticket is for component to remove the dependency on hare path hardcoded in the code so that symlink can be removed.
If it is already done in your component then mark this ticket resolved not required anymore.
Once all required components have made the changes. The code for creating the symlink during installation will be removed and no workaround required for consul binaries.
</code>
</pre>
<pre>
<code>
Provisioner installs consul and binary will be available in /usr/bin
</code>
</pre>
<pre> …

EOS-14380: Remove dependency of Consul hardcoded path inside Hare and move to /usr/bin/consul - SSPL - (main)

---

low-level/framework/base/sspl_constants.py
low-level/sensors/impl/generic/raid_integrity_data.py

…d setups
<pre>
<code>
Multiple Alerts seen for RAIDIntegritySensor
</code>
</pre>
<pre>
<code>
RAID Integrity Alerts seen recursively on all fresh deployed setups
</code>
</pre>
<pre>
<code>
Done required changes in RAIDIntegritySensor
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14712:RAID Integrity Alerts seen recursively on all fresh deployed setups

---

low-level/framework/rabbitmq/rabbitmq_egress_processor.py

calling str(sig.raw) without encoding calls `__str__` method on object
which is returns printable representation of string ex. "'None'" and
converting this to json string escapes internal ' with \
ex. '"b\'None\'"'. This creates invalid json.
using encoding 'utf-8' while converting to str will solve the issue
as sig.raw returns bytes and bytes.decode() and str(bytes, encoding)
is equivalent.
<pre>
<code>
Story Ref (if any): [EOS-14904](https://jts.seagate.com/browse/EOS-14904)
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code> …

EOS-14904: Use 'utf-8' while converting signature to string

---

low-level/framework/platforms/realstor/realstor_enclosure.py

<pre>
<code>
With FW G280 - No controller alert are observed on  GUI   
</code>
</pre>
<pre>
<code>
With FW G280 - No controller alert are observed on  GUI   
</code>
</pre>
<pre>
<code>
Added a fix to handle the error "Invalid sessionkey"  that comes in the HTTP rquest having the status HTTP_OK
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Testing will be done on hardware
</code>
</pre>

Changes for  EOS-14730 : 5U84 FW G280 - No controller alert observed on  GUI

---

low-level/json_msgs/messages/sensors/host_update.py
low-level/tests/manual/mock-halon.py
sspl_test/alerts/os/test_node_host_data_sensor.py

triggered as system alert.
<pre>
<code>
EOS-14403: Alert name issue on GUI: instead of memory alert, alert triggered as system alert. (main branch patch)
</code>
</pre>
<pre>
<code>
Resource type node:os:system was used for the alert so it was not clear that the alert was for system memory 
</code>
</pre>
<pre>
<code>
Modified the resource type in node_data_msg_handler - HostUpdateMsg from node:os:system to node:os:system_memory
</code>
</pre>
<pre>
<code>
- Yes
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14403: Alert name issue on GUI: instead of memory alert, alert triggered as system alert.

---

sspl_test/framework/base/sspl_constants.py
sspl_test/framework/utils/encryptor.py
sspl_test/rabbitmq/rabbitmq_egress_processor.py
sspl_test/rabbitmq/rabbitmq_ingress_processor_tests.py
sspl_test/run_qa_test.sh

<pre>
<code>
None
</code>
</pre>
<pre>
<code>
Currently SSPL test uses hardcoded RMQ credentials
</code>
</pre>
<pre>
<code>
Made changes to read credentials from Consul
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Remove hardcoding of RMQ credentials in SSPL test (#224)

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view
low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init
low-level/framework/platforms/realstor/realstor_enclosure.py

<pre>
<code>
Health view script is failing when forbidden error came from cotroller api's
</code>
</pre>
<pre>
<code>
Health view script is failing when forbidden error came from cotroller api's
</code>
</pre>
<pre>
<code>
Added some more validation checks to retry in controller login during hel tview generation
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-13209 : eos-13209-main-Add-retry-in-controller-login-during-healthview-generation

---

low-level/files/opt/seagate/sspl/bin/sspl_config
low-level/framework/sspl_rabbitmq_reinit

Signed-off-by: Madhura Mande <madhura.mande@seagate.com>
<pre>
<code>
Make SSPL compatible with latest RabbitMQ stable version  
</code>
</pre>
<pre>
<code>
RabbitMQ configuration script was failing for RabbitMQ version 3.8.9. some assert statements were failing which was version specific. 
</code>
</pre>
<pre>
<code>
Remove assert statements which are specific to version.
Make code independent of any version
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Its all tested with new RabbitMQ version on VM and HW
</code>
</pre>

Add support for RabbitMQ 3.8.9 (#231)

---

high-level/sspl_hl.spec
libsspl_sec/libsspl_sec.spec
low-level/cli/sspl_cli.spec
low-level/sspl-ll.spec
sspl_test/sspl-test.spec
test/sspl-test.spec

<pre>
<code>
EOS-15736
</code>
</pre>
<pre>
<code>
License value in SSPL rpms does not match expected value
</code>
</pre>
<pre>
<code>
Changed value to "Seagate" in rpm spec files
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-15736 : Change License text in SSPL rpms

---

low-level/sensors/impl/centos_7/systemd_watchdog.py

<pre>
<code>
Improve local and remote storage disk detection
</code>
</pre>
<pre>
<code>
Physical disks were detected by checking the WWN (If starts with 0x5) and then the out of this local disks detected by checking "Ata" and firmware version. 
</code>
</pre>
<pre>
<code>
added Hdparm utility for node disk detection.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
-  Simulated node disk alerts using:
Remove example:  echo 1 > /sys/block/sda/device/delete
Plug back in example: echo "0 0 0" >  /sys/class/scsi_host/host1/scan
- Recived fault,missing,insertion alerts for node disk.
</code>
</pre>

EOS-13435: Improve local and remote storage disk detection

---

low-level/framework/sspl_ll_d
sspl_test/coverage/coverage_code
sspl_test/coverage/start_sspl_coverage.sh
sspl_test/coverage/stop_sspl_coverage.sh

<pre>
<code>
To automate the SSPL code Coverage report generation
</code>
</pre>
<pre>
<code>
Write scripts for automation of coverage report generation
</code>
</pre>
<pre>
<code>
Added 3 files at  cortx-monitor/sspl_test/coverage and added comments in sspl_ll_d file
1st file => coverage_code : this file has the code snippet that needs to be inserted into sspl_ll_d for enabling 
coverage generation
2nd file => start_sspl_coverage.sh : this is the script file which sets up the environment for coverage report 
generation. After executing this script we can perform all the necessary tests for sspl, it 
will trace all the files during testing.
3rd file => stop_sspl_coverage.sh : After successful execution of tests on sspl, this script should be run to 
generate the coverage report and to …

EOS-15983: Automate code coverage

---

low-level/framework/rabbitmq/rabbitmq_egress_processor.py

… empty)
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
- [ * ] Yes
</code>
</pre>
[root@ssc-vm-2215 cortx-monitor]# low-level/tests/manual/rabbitmq_reader.py sspl-out sensor-key
^[[A
{"title": "SSPL Sensor Response", "description": "Seagate Storage Platform Library - Sensor Response", "username": "sspl-ll", "signature": "None", "time": "1613124954", "expires": 3600, "message": {"sspl_ll_msg_header": {"schema_version": "1.0.0", "sspl_version": "1.0.0", "msg_version": "1.0.0"}, …

EOS-17546: Alert Sequence Bug  

---

sspl_test/alerts/os/simulate_network_interface.py
sspl_test/alerts/os/test_disk_space_alert.py
sspl_test/alerts/os/test_node_if_data_sensor.py

The wait time added before looking for message in RMQ ingress processor queue was 10 sec.
While re-running the corresponding failed tests, debug log shows that message is put in queue after 14 sec.
At this time, while loop never enters in as queue is empty.
Also, added resource_type validation.

EOS-13375: Stabilize Failing Sanity Tests on Jenkins

---

low-level/sensors/impl/generic/node_sas_port.py

CSM UI
<pre>
<code>
SAS Port resolved alerts are not coming up on rabbitmq and CSM UI
</code>
</pre>
<pre>
<code>
"description" variable referenced before assignment.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-18452: SAS Port resolved alerts are not coming up on rabbitmq and CSM UI

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml
low-level/sensors/impl/platforms/realstor/realstor_dg_volume_sensor.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
Optimize Disk Group health check frequency
</code>
</pre>
<pre>
<code>
The default polling frequency for realstor_dg_volume_sensor is 30sec. Optimize it to 10sec. 
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-18520: Optimize Disk Group health check frequency

---

conftest.py
pytest.ini
unittests/conftest.py
unittests/framework/base/test_configuration_upgrade.py
unittests/message_handlers/test_service_msg_handler.py
unittests/test_service_monitor.py

unittest base framework required for SSPL.
pytest a popular third party library that is used for unittest.
* it is compatible with python's standard unittest library. So no extra learning curve for beginners.
* It is easier to set python paths via config.
* It is easier to specify multiple test directories via config.
* pytest fixtures are very useful in creating reusable test data (https://docs.pytest.org/en/6.2.x/fixture.html#fixtures)
* It is widely used among open source projects.
cd to the SSPL root directory and run the command
`pytest`
output:
```
→ pytest
......                                                                                                 [100%]
6 passed in 1.11s
```

Unittest base structure with pytest

---

low-level/files/opt/seagate/sspl/setup/setup_logger.py
low-level/files/opt/seagate/sspl/setup/sspl_setup.py

SSPL: Setup log is not created and error info lost during post_install failure
The Bug is non reproducible. Error Logs are getting generated.
Adding StreamHandler Logger to get the console output as well.
yes

EOS-20921: Add StreamHandler Logger to get logs on the console

---

low-level/files/opt/seagate/sspl/bin/generate_sspl_bundle/sspl_bundle_generate

Support bundle cache is not deleted due to someone has forcefully stopped/deleted support bundle service or restarted the system in between. That's why the new request is declined for the SSPL support bundle. because it is assuming that the old request is already going on on the basis of the existing cache.
​if we do for the fresh system. that error will not come.
​after completion of the support bundle request, all those files have been deleted automatically by the SSPL support bundle script.

EOS-21241 : SMS2-Build 631-Support bundle generation failed for sspl

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml

Removed old hare consul services from monitoring list along with haporxy service monitoring since it is not in sspl monitoring scope.

EOS-21975 Removed haproxy, and hare-consul-agaentc1/c2 from external services monitoring list.

---

low-level/framework/messaging/egress_accumulated_msgs_processor.py
low-level/framework/utils/filestore.py

Node down IEM/Alert is lost in SSPL.
1. We were getting below the errors while  reading/flushing msgs from accumulated queue. 
**'WARNING Error[a bytes-like object is required, not 'str'] while dumping data to file /var/cortx/sspl/data/SSPL_UNSENT_MESSAGES/MESSAGES/2 '**
**Expecting value: line 1 column 1 (char 0)**
Cause of error:  we open file in byte mode (wb) and trying to add string type value into flle.

EOS-21171: Node down IEM/Alert is lost in SSPL.

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml

Jira :[ EOS-22214](https://jts.seagate.com/browse/EOS-22214)
global_config_copy_url was not present in default config file. So, conf_upgrade script treated that as removed key and hence it was not added into existing config file. SSPL service failed because of this
Add global_config_copy_url in default config file with "" value

EOS-22214: Fix adaptive config

---

low-level/message_handlers/node_data_msg_handler.py

Fault resolved alert for CPU/memory usage should wait for certain waiting threshold time.
Introduced waiting time for CPU/memory usage fault resolved alerts.

EOS-21004: Introduce waiting time for CPU and memory usage fault resolved alert

---

low-level/files/opt/seagate/sspl/setup/sspl_setup.py
low-level/framework/base/conf_upgrade.py
low-level/sspl-ll.spec

Jira: [EOS-19805](https://jts.seagate.com/browse/EOS-19805)
Enabled non-disruptive sw upgrade through sspl mini-provisioner upgrade interface
- Currently configuration upgrade from rpm spec file. That needs to be done from upgrade interface
- Implement upgrade class in sspl_setup

EOS-19805: Add mini provisioner upgrade interface

---

low-level/files/opt/seagate/sspl/setup/sspl_post_install.py

Failed to restart rsyslog.service during SSPL deployment - post_install stage
This is observed as an intermittent issue. When we rerun the same command the issue wont occur again.
Wait and retry restarting rsyslog.service
For major feature, post the link to the solution page on the confluence Monitor team's space  -->

EOS-22560: Failed to restart rsyslog.service during post_install stage

---

low-level/framework/messaging/egress_accumulated_msgs_processor.py
low-level/framework/messaging/egress_processor.py
low-level/framework/messaging/ingress_processor.py
low-level/framework/utils/store_queue.py
sspl_test/messaging/egress_processor_tests.py
sspl_test/messaging/ingress_processor_tests.py

Instance creation for MessageProducer class failed when kafka is down on all three nodes.

EOS-21171:Node down IEM/Alert is lost in SSPL

---

low-level/files/opt/seagate/sspl/conf/sspl-ll.service.LR2

EOS-22363:SSPL systemd resource start/stop timing requirements for HA

---

low-level/framework/platforms/server/raid.py

Jira: [EOS-22969](https://jts.seagate.com/browse/EOS-22969)
Raid health filter for DEGRADED is not working
Changed Degraded/Fault to DEGRADED/FAULT

EOS-22969: Fix raid health

---

low-level/framework/base/sspl_constants.py
low-level/solution/lr2/server/health.py
low-level/solution/lr2/storage/health.py

EOS-23172: Description seen as 'N/A' for healthy Storage controller

EOS-23172: Description seen as 'N/A' for healthy Storage controller

---

low-level/files/opt/seagate/sspl/setup/sspl_reset.py

Factory reset interface deletes the log files for SSPL, so logs will not be generated untill rsyslog.service restarts
Clear log data instead of deleting the files

EOS-19806: Factory reset clear log data instead deleting log files.

---

low-level/framework/messaging/egress_accumulated_msgs_processor.py
low-level/framework/utils/iem.py
low-level/sspl_ll_d

Sometimes fault resolved alert when kafka service recovers from failure is not reported on message bus.
Cause of issue:
- For kafka service failure we send the iem alert and for generating iem, in service_monitor class we are calling 'self.iem.iem_fault("KAFKA_NOT_ACTIVE")'  from iem.py file.
- but in case of kafka service unavailability 'EventMessage.send' (from iem.py file) fails with 'KafkaError'.  this is not getting handled in 'EventMessageError' exception. 'serviceMonitor' which is calling this method shutdown because of this unhandled exception and hence we are not receiving alerts for service state change.
Fix:
- Added exception handling in iem.py.

EOS-20848:Stable 191: R2 : Sometimes fault resolved alert for kafka service is not reported.

---

low-level/framework/utils/mon_utils.py
low-level/solution/lr2/server/health.py
low-level/solution/lr2/server/manifest.py
low-level/solution/lr2/server/server_resource_map.py
low-level/solution/lr2/storage/health.py
low-level/solution/lr2/storage/manifest.py
low-level/solution/lr2/storage/storage_resource_map.py

--> disk and psu server manifest resources align done.

EOS-22875: Align Manifest/Health resource list with System resource map

---

low-level/solution/lr2/server/health.py
low-level/solution/lr2/server/manifest.py

EOS-22875: Resolved sorting/mapping discrepancy for server nw_port resource.

---

low-level/framework/sspl_reinit

Puppet-agent is deleting the /etc/sudoers.d/sspl file since the cmd to write noop = true has some issues. correction regarding the same is needed.

EOS-23581: Prevent `/etc/sudoers.d/sspl` file deletion

---

low-level/framework/messaging/egress_accumulated_msgs_processor.py
low-level/framework/utils/iem.py
low-level/sspl_ll_d

No alerts seen for  kafka service failure and also observed iem errors in sspl.logs.
- If kafka service failed EventMessage class initialization failed with kafkaerror.
- This exception is not handled in EventMessageError - added Exception handling for this in sspl_ll_d.
- before sending accumulated iem_msg, need to check if  EventMessage is initialized or not, if not initialize it first and then send iem.

EOS-23612:no alerts seen after disabled/enabled a kafka service

---

low-level/sensors/impl/centos_7/disk_monitor.py

There are 2 cases of persistent cache one of them is handled the second case is not handled, 
As per my observation,
1. If a drive is not present in the persistent cache and we insert the disk when sspl is off, we get disk insertion alert when sspl starts.
2. If a drive is present in the persistent cache and we remove the disk when sspl is off, we don't get the disk removal alert when sspl starts.
Handle the second case explained in Problem Statement.
Add information about drives in cache, so that when drive is removed during sspl inactivity, we will stil have the information about drive removed even when it's inaccesible.

EOS-23333: DiskMonitor Persistent Cache Issue

---

cortx-monitorQuickstartGuide.md
low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy

Signed-off-by: Thavanathan Thangaraj <thavanathan.thangaraj@seagate.com>
SSPL should be able to deploy outside Seagate network
We set Cortx repo locally and dev deploy script has been updated to use local build repo.
-----
[View rendered cortx-monitorQuickstartGuide.md](https://github.com/thavanathan/cortx-monitor/blob/qsg/cortx-monitorQuickstartGuide.md)

EOS-23381 SSPL: Fix scripts that require access to Seagate's internal repo

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml
low-level/sensors/impl/centos_7/service_monitor.py
sspl_test/alerts/os/test_service_monitor_sensor.py
unittests/test_service_monitor.py

For External services for major state transitions, alerts are raised immediately, HA will take action based on alerts.
But there is a possibility that systemd may be trying to recover the service as per the service file configs already, which would make service active quickly and HA may not need to take any action. 
Introduce threshold_wait time before raising alert for external service major state transition.

EOS-23183: LDR R2 SSPL: Sw Services monitoring - introduce configurable wait time before raising alert
