low-level/message_handlers/node_data_msg_handler.py

Alerts published by RMQ is not received by CSM due to jsonMsg syntax validation failure.
Event field is set to None. Fix is to mention event field to empty string.

EOS-13610 - Mgmt network alert not coming and as a result no failover happened

---

low-level/message_handlers/node_data_msg_handler.py

**Changes to cortx-1.0:**
Alerts published by RMQ is not received by CSM due to jsonMsg syntax validation failure.
Event field is set to None. Fix is to mention event field to empty string.

EOS-13610 - Mgmt network alert not coming and as a result no failover happening (cortx-1.0)

---

low-level/framework/base/sspl_constants.py
low-level/framework/sspl_reinit
low-level/sensors/impl/generic/raid_integrity_data.py

<pre>
<code>
Story Ref (if any): EOS-13178
Address errors seen with Server RAID Array integrity sensor
</code>
</pre>
<pre>
<code>
Address errors seen with Server RAID Array integrity sensor
</code>
</pre>
<pre>
<code>
Change in RAIDIntegritySensor.
</code>
</pre>
<pre>
<code>
- [1] Yes
</code>
</pre>
<pre>
<code>
/opt/seagate/cortx/sspl/sspl_test/run_tests.sh
</code>
</pre>

Address errors seen with Server RAID Array integrity sensor

---

low-level/framework/sspl_ll_d
low-level/framework/sspl_reinit
low-level/framework/utils/utility.py
sspl_test/run_test.py

<pre>
<code>
Story Ref (if any): EOS-13684
SSPL sync issue to read Provisioner python API
</code>
</pre>
<pre>
<code>
SSPL is not reading the setup values properly
</code>
</pre>
<pre>
<code>
Change the Provisioner API call path
More error Handling
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Check whether SSPL is picking right values from Provisioner API
Check whether Modules are enabled or not based on Environment
</code>
</pre>

Eos 13684 updated

---

low-level/sensors/impl/generic/node_sas_port.py

<pre>
<code>
https://jts.seagate.com/browse/EOS-13515
</code>
</pre>
<pre>
<code>
SAS Port/Cable removal/defect should generate alerts
</code>
</pre>
<pre>
<code>
Added port level alerts
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-13515: SAS Port/Cable removal/defect should generate alerts

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view

<pre>
<code>
</code>
</pre>
<pre>
<code>
Update SAS connection healthview schema based on updates to the SAS connection alerts
</code>
</pre>
<pre>
<code>
I have made the changes in health view node SAS data according to requirements
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-13600 : Update SAS connection healthview schema based on updates to the SAS connection alerts

---

low-level/message_handlers/node_data_msg_handler.py
low-level/sensors/impl/centos_7/systemd_watchdog.py
low-level/sensors/impl/generic/iem_sensor.py
sspl_test/run_test.py

- use common config for node_id, cluster_id, site_id
- fix bug in interface_added function
<pre>
<code>
https://jts.seagate.com/browse/EOS-13713
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-13713: Fix systemdwatchdog sensor for disk alerts

---

low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
low-level/framework/sspl_init

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOEOS-13611 : decryption was failing with 'unable to get key' error

---

low-level/sensors/impl/generic/node_sas_port.py

<pre>
<code>
EOS-13515
</code>
</pre>
<pre>
<code>
Porting this commit to main branch
</code>
</pre>
<pre>
<code>
-
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-13515: SAS Port/Cable removal/defects should generate alert (#164)

---

low-level/framework/utils/salt_util.py
low-level/framework/utils/utility.py

<pre>
<code>
EOS-13776: SSPL: Failover/Failback downtime improvement
</code>
</pre>
<pre>
<code>
SSPL is taking more than expected time to get started.
</code>
</pre>
<pre>
<code>
Internally SSPL uses salt-call to fetch some config values which gets hang and cause delay.
Replacing those with Prov API helps to reduce this delay
</code>
</pre>
<pre>
<code>
- Yes
</code>
</pre>
<pre>
<code>
Disable and enable the resource
Start stop sspl service
Node Reboot to test failover
</code>
</pre>

EOS-13776: SSPL: Failover/Failback downtime improvement

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view

…added version field in health view schema
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14145 : Replaced hostname with salt id(srvnode-1, srvnode-2) and added version field in health view schema

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view

…) and added version field in health view schema
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14145 : Main :Replaced hostname with salt id(srvnode-1, srvnode-2) and added version field in health view schema

---

sspl_test/alerts/self_hw/test_self_hw_node_sel_event.py

<pre>
<code>
EOS-14249
</code>
</pre>
<pre>
<code>
Sanity bug
</code>
</pre>
<pre>
<code>
Updated test case
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14249: bug fix in sanity

---

sspl_test/alerts/self_hw/test_self_hw_node_sel_event.py

<pre>
<code>
EOS-14249
</code>
</pre>
<pre>
<code>
Bug in sanity test case
</code>
</pre>
<pre>
<code>
Updated test case to handle change in fan alerts
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Updated node_sel_event test case to handle changes in fan alert (#203)

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view
low-level/sensors/impl/platforms/realstor/realstor_logical_volume_sensor.py

<pre>
<code>
EOS-12166
</code>
</pre>
<pre>
<code>
Health field shows the value "OK" even the alert_type = fault and severity = critical for logical_volume alert
</code>
</pre>
<pre>
<code>
Changes to logical volume sensor to send alerts based on logical volume health instead of disk group health
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-12166: Health field shows the value "OK" even the alert_type = fault and severity = critical for logical_volume alert

---

low-level/files/opt/seagate/sspl/bin/consuldump.py
low-level/files/opt/seagate/sspl/bin/generate_sspl_bundle/sspl_bundle_generate
low-level/framework/platforms/realstor/realstor_enclosure.py

<pre>
<code>
EOS-14030, EOS-14031, EOS-14111 : Import IPMI SEL, Server OS boot drives SMART data and sspl/ consul dump in Support Bundle
</code>
</pre>
<pre>
<code>
Missing some support bundle data (IPMI sel, Server OS boot drives SMART data, and sspl/ consul dump)
</code>
</pre>
<pre>
<code>
Import IPMI SEL, Server OS boot drives SMART data and sspl/ consul dump in Support Bundle
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14030, EOS-14031, EOS-14111 : Import IPMI SEL, Server OS boot drives SMART data and sspl/ consul dump in Support Bundle

---

sspl_test/framework/base/sspl_constants.py
sspl_test/framework/utils/encryptor.py
sspl_test/rabbitmq/rabbitmq_egress_processor.py
sspl_test/rabbitmq/rabbitmq_ingress_processor_tests.py
sspl_test/run_qa_test.sh

<pre>
<code>
EOS-14597
</code>
</pre>
<pre>
<code>
Sanity test fails because of RMQ connection issue
</code>
</pre>
<pre>
<code>
Use actual credential values instead of default
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

SSPL Test to use actual RMQ credentials

---

low-level/files/iec_mapping/ha

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>
<pre>
<code>
https://jts.seagate.com/browse/EOS-14341
</code>
</pre>
<pre>
<code>
Please add Problem description here...
Add io failover and failback iem
</code>
</pre>
<pre>
<code>
Please add summary of the change, List any dependencies that are required for this change.
No Dependencies 
</code>
</pre>
<pre>
<code>
- No
</code>
</pre>
<pre>
<code>
Tested on system. But not unit test.
</code>
</pre>

Add iem to detect failover and failback

---

low-level/files/iec_mapping/ha

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>
<pre>
<code>
https://jts.seagate.com/browse/EOS-14341
</code>
</pre>
<pre>
<code>
Please add Problem description here...
Add io failover and failback iem
</code>
</pre>
<pre>
<code>
Please add summary of the change, List any dependencies that are required for this change.
No Dependencies 
</code>
</pre>
<pre>
<code>
- No
</code>
</pre>
<pre>
<code>
Tested on system. But not unit test.
</code>
</pre>

Update resource iem for ha

---

low-level/files/opt/seagate/sspl/bin/manifest_support_bundle

<pre>
<code>
Improvment :  Restructured summery manifest file and added lr-serial-number.
</code>
</pre>
<pre>
<code>
Improvment :  Restructured summery manifest file and added lr-serial-number.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14514 : Include serial number in manifest support bundle

---

low-level/files/opt/seagate/sspl/bin/manifest_support_bundle

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14514 : Main - Included lr Serial number in manifest support bundle

---

low-level/sspl-ll.spec

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14803 Main: Adding lshw in sspl-ll Requires pkgs

---

low-level/sspl-ll.spec

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14803 Cortx-1.0: Adding lshw in sspl-ll Requires pkgs

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view
low-level/sensors/impl/centos_7/systemd_watchdog.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14816 : Node disk insertion alerts created on SSPL fresh boot

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view
low-level/framework/utils/filestore.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14963 : Sanity failure for build 405

---

low-level/files/opt/seagate/sspl/bin/sspl_config
low-level/framework/base/sspl_constants.py
low-level/framework/utils/salt_util.py

<pre>
<code>
EOS-14233
</code>
</pre>
<pre>
<code>
After node replacement, sspl is in stopped state on replaced node
</code>
</pre>
<pre>
<code>
Store minion id, consul host and port in conf file during sspl_config
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Store minion id, consul host and port in conf file during sspl_config

---

low-level/files/opt/seagate/sspl/bin/sspl_config
low-level/framework/sspl_rabbitmq_reinit

<pre>
<code>
Make SSPL compatiblw with latest RabbitMQ stable version
</code>
</pre>
<pre>
<code>
RabbitMQ configuration script was failing for RabbitMQ version 3.8.9. some assert statements were failing which was version specific. 
</code>
</pre>
<pre>
<code>
Foe now, removed that assert.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Install RabbitMQ 3.8.9 with its required dependency like erlang >= 22.x
Install and run SSPL
Perform SSPL sanity
</code>
</pre>

Rabbitmq upgrade

---

low-level/files/opt/seagate/sspl/bin/manifest_support_bundle

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-15032 : Corrected Chassis Serial Number in Manifest file

---

low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view
low-level/files/opt/seagate/sspl/bin/generate_resource_health_view/resource_health_view_template.json
low-level/sensors/impl/centos_7/systemd_watchdog.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14816 : Main : Adding node os drives cache and updating health view json file

---

low-level/files/opt/seagate/sspl/bin/manifest_support_bundle

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-15032:Main:Corrected Chassis Serial Number in Manifest file

---

low-level/message_handlers/node_data_msg_handler.py
low-level/sensors/impl/centos_7/systemd_watchdog.py
low-level/sensors/impl/generic/cpu_fault_sensor.py
low-level/sensors/impl/generic/iem_sensor.py
low-level/sensors/impl/generic/node_hw.py
low-level/sensors/impl/generic/node_memory_fault.py
low-level/sensors/impl/generic/node_sas_port.py
low-level/sensors/impl/generic/raid.py
low-level/sensors/impl/generic/raid_integrity_data.py
low-level/sensors/impl/platforms/realstor/realstor_controller_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_disk_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_enclosure_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_fan_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_logical_volume_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_psu_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_sideplane_expander_sensor.py

<pre>
<code>
PR for main branch: LDR R1 SSPL - dump monitored resource alerts to default INFO log level.
</code>
</pre>
<pre>
<code>
Monitored alerts needs to be dumped to default INFO log level, currently its dumped in DEBUG log level.
</code>
</pre>
<pre>
<code>
for alert -changed log level from debug to info in all sensors code.
</code>
</pre>
<pre>
<code>
- [X ] Yes
</code>
</pre>
<pre>
<code>
</code>
</pre>

Eos 14320 : dump monitored resource alerts to default INFO log level for main.

---

low-level/files/opt/seagate/sspl/bin/conf_based_sensors_enable
low-level/files/opt/seagate/sspl/bin/sspl_config
low-level/files/opt/seagate/sspl/bin/sspl_post_install
low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init
low-level/files/opt/seagate/sspl/conf/sspl.conf.LDR_R1
low-level/files/opt/seagate/sspl/conf/sspl.conf.LDR_R2
low-level/framework/base/sspl_constants.py
low-level/framework/rabbitmq/thread_controller.py
low-level/framework/sspl_ll_d
sspl_test/framework/utils/config_reader.py
sspl_test/plans/alerts.pln
sspl_test/plans/sanity.pln
sspl_test/plans/self_primary.pln
sspl_test/run_test.py
sspl_test/sspl_tests.conf

…
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-12131: SSPL: JBOD: Deployment: Control the list of resources to monitor (other monitoring/HA turned off)

---

low-level/framework/rabbitmq/thread_controller.py
low-level/framework/sspl_ll_d
low-level/sensors/impl/platforms/realstor/realstor_dg_volume_sensor.py

<pre>
<code>
EOS-14232
</code>
</pre>
<pre>
<code>
Introduce alert for disk group fault
</code>
</pre>
<pre>
<code>
Added logic to logical volume sensor to also check for disk group faults
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-14232 : Introduce alert for disk group fault

---

low-level/files/opt/seagate/sspl/bin/manifest_support_bundle

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-15575 : JSON structures in Manifest file

---

low-level/files/opt/seagate/sspl/bin/manifest_support_bundle

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-1777 : JSON structures in Manifest file

---

jenkins/build.sh
libsspl_sec/libsspl_sec.spec
low-level/cli/sspl_cli.spec
low-level/sspl-ll.spec
sspl_test/sspl-test.spec

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-16305 : SSPL RPM generation are failing due to different repo name except cortx-sspl.

---

low-level/files/opt/seagate/sspl/setup/sspl_setup.py
low-level/files/opt/seagate/sspl/setup/sspl_test.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Added --config flag for future use-case
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Added '--config' flag support for both sspl_test and sspl_reset scripts

---

low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

In sspl_dev_deploy, reload site. So newly added packages can be imported

---

low-level/files/opt/seagate/sspl/conf/setup.yaml

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Update setup.yaml with latest provisioner spec

---

low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy
low-level/framework/utils/salt_util.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Fix for sspl_dev_deploy --cleanup cmd.

---

low-level/message_handlers/node_data_msg_handler.py

… failure)
Signed-off-by: root <root@ssc-vm-2215.colo.seagate.com>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

<fix>EOS-17205-test_node_host_data_sensor (fixed the bug causing test failure)

---

low-level/files/opt/seagate/sspl/conf/setup.yaml

- change <URL> to $URL
- align support_bundle
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Fix setup.yaml

---

README.md

Added the Slack and Youtube badge.
Signed-off-by: Mayur Gupta <mayur.gupta@seagate.com>
-----
[View rendered README.md](https://github.com/TechWriter-Mayur/cortx-monitor/blob/main/README.md)

Added the Slack and Youtube badge

---

low-level/files/opt/seagate/sspl/bin/generate_sspl_bundle/sspl_bundle_generate

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-17348 : Cortx-1.0 - Changed sspl support bundle temporary file location.

---

low-level/files/opt/seagate/sspl/setup/generate_sspl_bundle/sspl_bundle_generate

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-17348 : Main - Changed sspl support bundle temporary file location.

---

low-level/framework/sspl_ll_d

<pre>
<code>
Added logger.exception in sspl_ll_d file for handling error traceback.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Added logger.exception in sspl_ll_d file for handling error traceback.

---

low-level/files/opt/seagate/sspl/setup/error.py
low-level/requirements.txt

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-17813: Fix string formatting for setup error exception

---

low-level/framework/rabbitmq/rabbitmq_egress_accumulated_msgs_processor.py
low-level/framework/rabbitmq/rabbitmq_egress_processor.py

<pre>
<code>
Dump alert messages to INFO log level.
</code>
</pre>
<pre>
<code>
For easy debugging dumped alert messages to info log level.
</code>
</pre>
<pre>
<code>
Added alert msgs in info log level.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Dump alerts to INFO log level.

---

low-level/sensors/impl/platforms/realstor/realstor_disk_sensor.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-17449 : Main-Disks alert observed in Active Alerts even if the disks are in fault.

---

low-level/files/opt/seagate/sspl/conf/sample_global_cortx_config.yaml
low-level/files/opt/seagate/sspl/setup/generate_resource_health_view/resource_health_view
low-level/framework/utils/conf_utils.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-16668 : Main-Resource health view to use ConfStore instead of consul

---

low-level/framework/sspl_ll_d
low-level/sensors/impl/generic/raid_integrity_data.py

<pre>
<code>
Story Ref (if any): EOS-18399
Improve the message displayed for "node:os:raid_integrity".
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Updated description for raid_integrity alert.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-18399: Improve the message displayed for "node:os:raid_integrity".

---

low-level/sensors/impl/generic/node_sas_port.py
low-level/sensors/impl/generic/raid_integrity_data.py
low-level/sspl_ll_d

<pre>
<code>
Story Ref (if any): EOS-18399, EOS-18452
- Improve the message displayed for "node:os:raid_integrity".
- SAS Port resolved alerts are not coming up on rabbitmq and CSM UI
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

main-branch-pr: fix for EOS-18399 and EOS-18452

---

low-level/actuators/impl/centos_7/systemd_service.py
low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml
low-level/files/opt/seagate/sspl/setup/sspl_config.py
low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy
low-level/files/opt/seagate/sspl/setup/sspl_post_install.py
low-level/files/opt/seagate/sspl/setup/sspl_reset.py
low-level/files/opt/seagate/sspl/setup/sspl_setup.py
low-level/files/opt/seagate/sspl/setup/sspl_test.py
low-level/framework/sspl_reinit
low-level/framework/utils/utility.py
low-level/json_msgs/messages/actuators/service_controller.py
low-level/json_msgs/messages/base_msg.py
low-level/json_msgs/schemas/actuators/SSPL-LL_Actuator_Response.json
low-level/message_handlers/service_msg_handler.py
sspl_test/alerts/os/test_systemd_service_actuator.py
sspl_test/plans/alerts.pln
sspl_test/plans/sanity.pln

…md. (#326)
* EOS-17636: Ability to control 3rd party software services using systemd.
* EOS-17636: Controlling 3rd party services using systemd.
* EOS-17636: Added 3rd party services list.
* EOS-17636: Ability to control 3rd party s/w service using systemd.
* EOS-17636: Ability to control 3rd party software services using systemd
* EOS-17636: Fixed codacy issue.
* EOS-17636: Ability to control 3rd party services.
Signed-off-by: …

EOS-17636: Ability to control 3rd party software services using systemd

---

low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

build url to pull the cortx-utils rpm is updated.

---

low-level/files/opt/seagate/sspl/conf/sample_global_cortx_config.yaml
low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-16342: Fix utils_setup steps

---

low-level/files/opt/seagate/sspl/setup/generate_sspl_bundle/sspl_bundle_generate

<pre>
<code>
</code>
</pre>
<pre>
<code>
Cleanup RMQ logs from support bundle
</code>
</pre>
<pre>
<code>
Removed the RMQ logs from support bundle
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS:18088: Cleanup RMQ logs from support bundle

---

low-level/sensors/impl/centos_7/service_monitor.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-16854: Proper Use Of Conf.get() in 3rd party s/w monitoring using  copy.deepcopy()

---

low-level/message_handlers/node_data_msg_handler.py

--> Adding persistent cache for network cable
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19075 : Network Cable Fault not resolved even when network interface working fine.

---

low-level/files/opt/seagate/sspl/bin/consuldump.py
low-level/files/opt/seagate/sspl/bin/generate_sspl_bundle/sspl_bundle_generate
low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init
low-level/framework/base/sspl_constants.py
low-level/sensors/impl/generic/raid_integrity_data.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-18905 : SSPL Support Bundle | Cleanup up temporary files even though an error happens while generating a support bundle.

---

low-level/files/opt/seagate/sspl/setup/sspl_config.py
low-level/framework/rabbitmq/__init__.py
low-level/framework/rabbitmq/logging_processor.py
low-level/framework/rabbitmq/rabbitmq_egress_accumulated_msgs_processor.py
low-level/framework/rabbitmq/rabbitmq_egress_processor.py
low-level/framework/rabbitmq/rabbitmq_ingress_processor.py
sspl_test/rabbitmq/__init__.py
sspl_test/rabbitmq/consume.py
sspl_test/rabbitmq/rabbitmq_egress_processor.py
sspl_test/rabbitmq/rabbitmq_ingress_processor_tests.py
sspl_test/sspl_start_checker

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-16355: Use singleton MessageBus class

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-18477 Add kafka service in sspl config to support control/monitoring

---

low-level/files/opt/seagate/sspl/setup/consuldump.py
low-level/files/opt/seagate/sspl/setup/generate_sspl_bundle/sspl_bundle_generate
low-level/framework/base/sspl_constants.py
low-level/sensors/impl/generic/raid_integrity_data.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-18905 : Main : SSPL Support Bundle | Cleanup up temporary files even though an error happens while generating a support bundle.

---

low-level/message_handlers/node_data_msg_handler.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19075 : Main - Adding persistent cache for Network Interface (Network Cable)

---

low-level/files/opt/seagate/sspl/setup/generate_sspl_bundle/sspl_bundle_generate
low-level/framework/base/sspl_constants.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-17800 : Support: Create Support Bundle LR2

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LDR_R1
low-level/framework/platforms/realstor/realstor_enclosure.py
low-level/message_handlers/node_data_msg_handler.py
low-level/sensors/impl/generic/node_data.py
low-level/sensors/impl/generic/raid.py
low-level/sensors/impl/generic/raid_integrity_data.py
low-level/sensors/impl/platforms/realstor/realstor_enclosure_sensor.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19093: Addition of Persistent Cache for Sensor Alerts (mainly node data)

---

low-level/files/iec_mapping/s3

<pre>
<code>
Update s3 IEC mapping for the new IEMs
</code>
</pre>
<pre>
<code>
s3 added two new IEMs for which the IEC mapping file should be updated.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Tested by manually modifying the s3 iec mapping file on HW setup and re-starting the SSPL.
</code>
</pre>

EOS-19528: Updated s3 iec mapping

---

low-level/framework/base/sspl_constants.py
sspl_test/plans/alerts.pln

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19581
Disabled RAIDIntegrity sensor.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Disabled RAIDIntegrity sensor.

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LR2.yaml
low-level/files/opt/seagate/sspl/setup/conf_based_sensors_enable.py
low-level/framework/platforms/realstor/realstor_enclosure.py
low-level/message_handlers/node_data_msg_handler.py
low-level/sensors/impl/centos_7/service_monitor.py
low-level/sensors/impl/generic/raid.py
low-level/sensors/impl/generic/raid_integrity_data.py
low-level/sensors/impl/platforms/realstor/realstor_enclosure_sensor.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19093:  Persistent Cache for the sensors LR2

---

low-level/actuators/impl/generic/realstor_encl.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19344 : main-shutdown-enclosure-actuator

---

low-level/files/opt/seagate/sspl/conf/sspl.conf.LDR_R1
low-level/framework/base/sspl_constants.py
low-level/framework/rabbitmq/thread_controller.py
low-level/framework/sspl_ll_d

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19808
Pull out sensor & actuator list in sspl config
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19808: Pull out sensor & actuator list in sspl config.(CortxV1 SMS2)

---

low-level/sensors/impl/generic/node_hw.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19807:Main - IPMITool | More monitoring for faulty resources.

---

low-level/sensors/impl/centos_7/service_monitor.py
unittests/test_service_monitor.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19584: ServiceMonitor - Monitor service in when service is enabled after SSPL starts

---

low-level/sensors/impl/generic/cpu_fault_sensor.py

Signed-off-by: Jeet Jain <jeet.jain@seagate.com>
<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-20626
</code>
</pre>
<pre>
<code>
Update resource_type in generated alert for CPU fault sensor
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Update resource_type in generated alert for CPU fault sensor

---

.github/pull_request_template.md

<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
-----
[View rendered .github/pull_request_template.md](https://github.com/thavanathan/cortx-monitor/blob/pr_template/.github/pull_request_template.md)

Updated github PR template

---

low-level/files/opt/seagate/sspl/setup/sspl_reset.py
low-level/files/opt/seagate/sspl/setup/sspl_setup.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
Need factory reset support through mini provisioner interface
</code>
</pre>
<pre>
<code>
Added support for Reset Interface for SSPL component
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-19806: Need factory reset support through mini provisioner interface

---

low-level/files/opt/seagate/sspl/setup/resource_map/storage.py

Collect Resource map, health, attributes as per schema for PSUs.
Added a function to generate PSUs health info as per required schema.

EOS-20938 SSPL Support on Storage PSUs Health Provider for DM

---

low-level/files/opt/seagate/sspl/setup/resource_map/storage.py
unittests/conftest.py
unittests/files/opt/seagate/sspl/setup/resource_map/test_storage.py

Temperature, Voltage, Current sensor data for storage DM.
Updated storage module to return above sensor data

EOS-20958 R2 System Health: Storage: HW: Temperature / Voltage / Current sensors

---

low-level/files/opt/seagate/sspl/setup/resource_map/storage.py
low-level/framework/base/sspl_constants.py

EOS-20957:R2 System Health: Storage: FW: Disk groups / Volumes

---

low-level/files/opt/seagate/sspl/setup/resource_map/resource_map.py
low-level/files/opt/seagate/sspl/setup/resource_map/server.py
low-level/framework/base/sspl_constants.py
unittests/files/opt/seagate/sspl/setup/resource_map/test_server.py

Signed-off-by: Thavanathan Thangaraj <thavanathan.thangaraj@seagate.com>
Health data for dm modules node server.
dm module's server.py updated to read ipmi data for platform sensors.

EOS-20928 R2 System Health: Server: HW: Temperature / Voltage / Current sensors

---

low-level/files/opt/seagate/sspl/setup/generate_sspl_bundle/sspl_bundle_generate

EOS-21241 : Main-SMS2-Build 631-Support bundle generation failed for sspl

---

low-level/files/opt/seagate/sspl/setup/resource_map/storage.py

EOS-20957 : System Health - Disk Group uid correction.

---

low-level/files/opt/seagate/sspl/setup/resource_map/server.py
unittests/files/opt/seagate/sspl/setup/resource_map/test_server.py

R2 System Health: Server: HW: Fan
Implemented fan-modules interface to get server fan health schema

EOS:20962: R2 System Health: Server: HW: Fan

---

low-level/files/opt/seagate/sspl/setup/resource_map/lr2/resource_map.py
low-level/files/opt/seagate/sspl/setup/resource_map/lr2/server.py
low-level/files/opt/seagate/sspl/setup/resource_map/lr2/storage.py
low-level/framework/base/sspl_constants.py
low-level/framework/utils/service_logging.py
low-level/framework/utils/utility.py
unittests/files/opt/seagate/sspl/setup/resource_map/lr2/test_server.py
unittests/files/opt/seagate/sspl/setup/resource_map/lr2/test_storage.py

Logging for Node health collection
Add Logging module for Node-Health Feature

Eos 21918: Logging for Node health collection

---

low-level/files/opt/seagate/sspl/setup/resource_map/lr2/server.py
low-level/files/opt/seagate/sspl/setup/resource_map/lr2/storage.py
unittests/files/opt/seagate/sspl/setup/resource_map/lr2/encl_api_response.py
unittests/files/opt/seagate/sspl/setup/resource_map/lr2/test_server.py
unittests/files/opt/seagate/sspl/setup/resource_map/lr2/test_storage.py

Signed-off-by: Thavanathan Thangaraj <thavanathan.thangaraj@seagate.com>
Fan modules health data
Updated storage.py with fan modules health data.
Added a new test for fan modules.

EOS-20939 R2 System Health: Storage: HW: Fans

---

low-level/files/opt/seagate/sspl/conf/sspl.post-install.tmpl.1-node
low-level/files/opt/seagate/sspl/conf/sspl.post-install.tmpl.1-node.sample
low-level/files/opt/seagate/sspl/conf/sspl.post-install.tmpl.3-node
low-level/files/opt/seagate/sspl/conf/sspl.post-install.tmpl.3-node.sample
low-level/files/opt/seagate/sspl/setup/resource_map/lr2/server.py
low-level/files/opt/seagate/sspl/setup/resource_map/lr2/storage.py
low-level/files/opt/seagate/sspl/setup/sspl_config.py
low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy
low-level/files/opt/seagate/sspl/setup/sspl_post_install.py
low-level/files/opt/seagate/sspl/setup/sspl_prepare.py
low-level/framework/platforms/server/platform.py
low-level/framework/platforms/server/software.py
low-level/framework/utils/utility.py

EOS-20937: Add storage and server information in resource_map

---

low-level/files/opt/seagate/sspl/setup/resource_map/lr2/server.py
low-level/framework/platforms/server/disk.py
low-level/framework/platforms/server/raid/raid.py
low-level/framework/utils/server_drives.py

EOS-20132: Health data for disks and psus

---

low-level/message_handlers/node_data_msg_handler.py

Signed-off-by: Jeet Jain <jeet.jain@seagate.com>
Improvements in fault description message for CPU/Memory/Disks usage
Improved alert statements as per suggestion from the QA

EOS-21002: Improvements in fault description message for CPU/Memory/Disks usage

---

low-level/message_handlers/node_data_msg_handler.py
low-level/sensors/impl/generic/node_hw.py

EOS-23009: Enable current sensor monitoring for node server.

---

low-level/framework/base/sspl_constants.py
low-level/framework/utils/iem.py
low-level/framework/utils/ipmi_client.py
low-level/sensors/impl/centos_7/disk_monitor.py
low-level/sensors/impl/centos_7/service_monitor.py
low-level/sensors/impl/generic/node_hw.py
sspl_test/alerts/node/test_node_bmc_interface.py
sspl_test/framework/base/sspl_constants.py
unittests/framework/utils/test_ipmi_tool.py

EOS-22358:Enable Server monitoring using IPMI over LAN Plus

---

low-level/sspl-ll.spec

EOS-17458: Change solution directory path after the SSPL deployment.

---

low-level/files/opt/seagate/sspl/setup/setup_yum_repos.py
low-level/files/opt/seagate/sspl/setup/sspl_dev_deploy

EOS-15400 Port SSPL to CentOS 7.9

---

CODEOWNERS

Updated CODEOWNERS as Gatekeepers

Updated CODEOWNERS as Gatekeepers

---

low-level/actuators/impl/generic/realstor_encl.py
low-level/framework/base/sspl_constants.py
low-level/framework/utils/mon_utils.py
low-level/json_msgs/messages/sensors/cpu_data.py
low-level/json_msgs/messages/sensors/disk_space_alert.py
low-level/json_msgs/messages/sensors/host_update.py
low-level/json_msgs/messages/sensors/iem_data.py
low-level/json_msgs/messages/sensors/if_data.py
low-level/sensors/impl/centos_7/disk_monitor.py
low-level/sensors/impl/centos_7/service_monitor.py
low-level/solution/lr2/server/health.py
low-level/solution/lr2/server/manifest.py
low-level/solution/lr2/server/server_resource_map.py
low-level/solution/lr2/storage/health.py
low-level/solution/lr2/storage/manifest.py
low-level/solution/lr2/storage/storage_resource_map.py
unittests/solution/lr2/server/test_server_manifest.py

Changed code of manifest and health as per SSPL Arch Roadmap discussion.
--> Change/Rename compute to a server in SSPL manifest and health code.
--> Change "NA" to "Not Applicable" those fields which are not applicable in software services.
--> Remove storage/enclosure disks from that disk type section. the only os saw disk are present.

EOS-17458: Restructuring minor code of manifest and health.

---

low-level/files/opt/seagate/sspl/conf/setup.yaml
low-level/files/opt/seagate/sspl/setup/sspl_setup.py

Jira: [EOS-20333](https://jts.seagate.com/browse/EOS-20333)
Add pre_update and post_upgrade section in setup.yaml

EOS-20333: Align setup.yaml with provisioner spec

---

low-level/sensors/impl/generic/node_hw.py
low-level/sensors/impl/generic/node_hw_alerts_info.py

EOS-23181: [server:hw:psu] Improve Description, add impact & recommendation.

---

low-level/sensors/impl/generic/node_hw.py
low-level/sensors/impl/generic/node_hw_alerts_info.py

Improve Alerts Description - Server FRU Alerts - Fans
Updated description & added 'impact' and 'recommendation' field to alert schema

EOS-23182: Improve Alerts Description - Server FRU Alerts - Fans

---

low-level/files/opt/seagate/sspl/setup/sspl_post_install.py
low-level/files/opt/seagate/sspl/setup/sspl_prepare.py

EOS-23527: SSPL post_install failed on network validation during CORTX deployment

---

low-level/framework/utils/conf_utils.py
low-level/sensors/impl/platforms/realstor/realstor_dg_volume_sensor.py
low-level/solution/lr2/storage/health.py

EOS-22846: LR R2 SSPL: Provide DG to CVG mapping Disk Group Alerts

---

low-level/files/opt/seagate/sspl/setup/sspl_post_install.py
low-level/framework/utils/conf_utils.py
sspl_test/sspl-test.spec

Ensure the SPPL deployment and functionality on hw server.
While testing on vm, I used some of the el7 rpms that worked fine, but we are not supposed to install them, so updated such pkgs for the validation.
Ensured the snity test on hw.

EOS-23319: Porting To Rocky Linux Hw

---

low-level/actuators/impl/generic/realstor_encl.py
low-level/files/opt/seagate/sspl/setup/generate_resource_health_view/resource_health_view
low-level/framework/platforms/realstor/realstor_enclosure.py
low-level/json_msgs/messages/sensors/realstor_encl_data_msg.py
low-level/message_handlers/real_stor_encl_msg_handler.py
low-level/sensors/impl/centos_7/disk_monitor.py
low-level/sensors/impl/generic/node_hw.py
low-level/sensors/impl/platforms/realstor/realstor_controller_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_dg_volume_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_disk_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_enclosure_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_fan_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_psu_sensor.py
low-level/sensors/impl/platforms/realstor/realstor_sideplane_expander_sensor.py
sspl_test/alerts/node/test_node_bmc_interface.py
sspl_test/alerts/realstor/test_real_stor_controller_actuator.py
sspl_test/alerts/realstor/test_real_stor_controller_sensor.py
sspl_test/alerts/realstor/test_real_stor_disk_actuator.py
sspl_test/alerts/realstor/test_real_stor_disk_sensor.py
sspl_test/alerts/realstor/test_real_stor_enclosure_sensor.py
sspl_test/alerts/realstor/test_real_stor_fan_actuator.py
sspl_test/alerts/realstor/test_real_stor_fan_sensor.py
sspl_test/alerts/realstor/test_real_stor_for_platform_sensor.py
sspl_test/alerts/realstor/test_real_stor_psu_actuator.py
sspl_test/alerts/realstor/test_real_stor_psu_sensor.py
sspl_test/alerts/realstor/test_real_stor_sideplane_actuator.py
sspl_test/alerts/realstor/test_real_stor_sideplane_expander_sensor.py
sspl_test/common.py
test/automated/features/real_stor_encl_actuator.py

EOS-23185: LR R2 SSPL: Align resource type in sensor/actuator data with that of Node Health - Storage Enclosure

---

low-level/requirements.txt

As per comment on [EOS-23495](https://jts.seagate.com/browse/EOS-23495?focusedCommentId=2182143&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2182143)
removed requirment.txt file as all pkgs mentioned in this file getting installed through cortx-prereq rpm.

EOS-23495: Test third-party package version upgrade PRs

---

low-level/files/opt/seagate/sspl/conf/support.yaml
low-level/solution/lr2/support_bundle/sspl_support_bundle

EOS-24122: Update support.yaml format to Interim format for support.yaml file

---

low-level/framework/utils/sysfs_interface.py
low-level/message_handlers/node_data_msg_handler.py
low-level/sensors/impl/generic/node_data.py

EOS-23324: nw & nw:cable alert Improvement

---

low-level/framework/platforms/server/software.py
sspl_test/alerts/realstor/test_real_stor_dg_sensor.py
sspl_test/functional_tests/v2/alerts/realstor/test_real_stor_dg_sensor.py

EOS-23497: Correction-Decided health of the service on the basis of state and substate.

---

low-level/solution/lr2/support_bundle/sspl_support_bundle

EOS-24017: Added SSPL directory at the end of the given path for SB generation.

---

low-level/files/opt/seagate/sspl/setup/sspl_post_install.py

- Use SimpleProcess instead of os.system to make sure exception raises when command fails
- Add retries in user validation

EOS-25084: Fix sspl-ll user validation
